spring.application.name=api-example
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/db_api_example
spring.datasource.username=postgres
spring.datasource.password=Markus11997

#UPDATE ONLY IN PRODUCTION
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernet.format_sql=true